import img1 from '../img/img1.jpg'
import img2 from '../img/img2.jpg'
import img3 from '../img/img3.jpg'
import img4 from '../img/img4.jpg'
import img5 from '../img/img5.jpg'
import img6 from '../img/img6.jpg'
import img7 from '../img/img7.jpg'
import img8 from '../img/img8.jpg'
import img9 from '../img/img9.jpg'

export default [
    {
        id: 1,
        url: 'croissant',
        name: 'Croissant',
        img: img1,
        price: 1.99,
        ingredients: ["500g strong white flour, plus extra for dusting", "50g sugar", "300g butter at room temperature",
            "1 eggbeaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: true,
        type: 'bread',

    },
    {
        id: 2,
        url: 'Seed-grain-cottage-loaf',
        name: 'Seed & grain cottage loaf',
        img: img2,
        price: 1.89,
        ingredients: ["2 tbsp clear honey", "100g strong white bread flour", "mixed seeds (we used sunflower, sesame, pumpkin and linseeds)", "25g butter cut into cubes",
            "1 egg, beaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: false,
        type: 'bread',
    },
    {
        id: 3,
        url: 'tiger-bread',
        name: 'Tiger bread',
        img: img3,
        price: 1.59,
        ingredients: ["2 tbsp clear honey", "100g strong white bread flour", "mixed seeds (we used sunflower, sesame, pumpkin and linseeds)", "25g butter cut into cubes",
            "1 egg, beaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: false,
        type: 'bread',
    },
    {
        id: 4,
        url: 'strawberry-cheesecake',
        name: 'Strawberry cheesecake',
        img: img4,
        price: 7.99,
        ingredients: ["100g icing sugar", "284ml pot of double cream", "mixed seeds (we used sunflower, sesame, pumpkin and linseeds)", "1 vanilla pod",
            "1 egg, beaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: false,
        type: 'cake',
    },
    {
        id: 5,
        url: 'new-york-cheesecake',
        name: 'New York cheesecake',
        img: img5,
        price: 7.99,
        ingredients: ["100g icing sugar", "284ml pot of double cream", "mixed seeds (we used sunflower, sesame, pumpkin and linseeds)", "1 vanilla pod",
            "1 egg, beaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: true,
        type: 'cake',
    },
    {
        id: 6,
        url: 'watermelon-lemonade',
        name: 'Watermelon lemonade',
        img: img6,
        price: 0.99,
        ingredients: ["small handful mint", "1l bottle soda water", "1 limecut into slices", "crushed ice",
            "1 egg, beaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: true,
        type: 'drink',
    },
    {
        id: 7,
        url: 'mint-lemonade',
        name: 'Mint lemonade',
        img: img7,
        price: 0.99,
        ingredients: ["small handful mint", "1l bottle soda water", "1 limecut into slices", "crushed ice",
            "1 egg, beaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: false,
        type: 'drink',
    },
    {
        id: 8,
        url: 'caffe',
        name: 'Caffe',
        img: img8,
        price: 2.99,
        ingredients: ["small handful mint", "1l bottle soda water", "1 limecut into slices", "crushed ice",
            "1 egg, beaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: true,
        type: 'drink',
    },
    {
        id: 9,
        url: 'bread',
        name: 'bread',
        img: img9,
        price: 2.99,
        ingredients: ["small handful mint", "1l bottle soda water", "1 limecut into slices", "crushed ice",
            "1 egg, beaten"],
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quae eius magni ut maxime voluptatem pariatur qui nesciunt modi necessitatibus, earum dignissimos commodi id. Suscipit natus asperiores consectetur aut nemo.",
        featured: false,
        type: 'bread',
    },
]